# This is expected to be _built_ with the project root as the context directory.
#
# Either of these:
#   podman build -f splicer-web/Containerfile .
#   git archive HEAD | podman build -f splicer-web/Containerfile -

FROM node:current-alpine

WORKDIR /splicer/web

ADD splicer-web/package.json \
    splicer-web/package-lock.json \
    .
RUN npm install

ADD splicer-web/index.html \
    splicer-web/tsconfig.json \
    splicer-web/vite.config.js \
    splicer-web/build-deploy.sh \
    .git-commit-hash \
    .
ADD splicer-web/src src
ADD splicer-web/public public
ADD splicer-web/assets/fonts.css \
    splicer-web/assets/palette.css \
    splicer-web/assets/style.css \
    splicer-web/assets/splicer.css \
    assets

RUN npm install -g wrangler

RUN rm -rf /root/.npm

ENTRYPOINT ["/splicer/web/build-deploy.sh"]

# vim: syntax=dockerfile
