# This is expected to be _built_ with the project root as the context directory.

FROM node:current-alpine

WORKDIR /publish/web

RUN apk update \
 && apk add --no-cache python3 py3-lxml # py3-pillow

ADD baro-data/baro-data.py \
    splicer/publish/splicer-publish.sh \
    .

ADD web/package.json \
    web/package-lock.json \
    .
RUN npm install

ADD web/index.html \
    web/tsconfig.json \
    web/vite.config.js \
    .git-commit-hash \
    .
ADD web/src src
ADD web/public public
ADD web/assets/fonts.css \
    web/assets/palette.css \
    web/assets/style.css \
    assets

RUN npm install -g wrangler

RUN rm -rf /root/.npm

ENTRYPOINT ["/publish/web/splicer-publish.sh"]

# vim: syntax=dockerfile
