# This is expected to be _built_ with the project root as the context directory.
#
# podman build -f path/to/this/Containerfile .

FROM registry.fedoraproject.org/fedora-minimal

# The path here is important it must be in sync with splicer-api,
# when that service creates this container, it writes files to
# /publish/web/assets/bundles before starting it.
WORKDIR /publish/web

RUN microdnf install -y python3 python3-lxml nodejs nodejs-npm \
 && microdnf clean all

ADD baro-data.py \
    splicer/publish/splicer-publish.sh \
    .

ADD web/package.json \
    web/package-lock.json \
    .
RUN npm install && npm install -g wrangler && rm -rf /root/.npm

ADD web/index.html \
    web/tsconfig.json \
    web/vite.config.js \
    .git-commit-hash \
    .
ADD web/src src
ADD web/public public
ADD web/assets/fonts.css \
    web/assets/palette.css \
    web/assets/style.css \
    assets

ENTRYPOINT ["/publish/web/splicer-publish.sh"]

# vim: syntax=dockerfile
