# This is expected to be _built_ with the project root as the context directory.
#
# podman build -f path/to/this/Containerfile .

FROM python:3-alpine

RUN apk update \
 && apk add podman-remote tar zstd

WORKDIR /materialist

RUN python -m venv venv --without-pip --system-site-packages

ADD splicer/steamcmd/materialist materialist
ADD splicer/steamcmd/ruff.toml \
    splicer/steamcmd/setup.cfg \
    splicer/steamcmd/setup.py \
    .

RUN /materialist/venv/bin/python -m pip install .

ENTRYPOINT ["/materialist/venv/bin/python", "-m", "materialist.steamcmd"]
